apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    app: gemini
  name: gemini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: gemini
    spec:
      containers:
      - env:
        - name: GEMINI_DB_PASSWORD
          value: password
        - name: GEMINI_DB_ROOT_PASSWORD
          value: password
        - name: GEMINI_JWT_ADMIN_TOKEN
          value: islandora
        - name: GEMINI_JWT_PUBLIC_KEY
          value: |-
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6uK3nozywVaRCAB3FHdR
            ZNHunSZvN/c31QimZAqQMGxj7JrGh1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2w
            ARr/9abIwG5QeNsrJ8GMt3Z/WICnNeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRK
            sk0BfFSMh+4u3JAdD9tUxUx6AAUXUCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80
            Xrrsu1PYATgrsy69stzCln3KlO5Oxc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9P
            a3SNje4UXN+/1xUfQskxafP8CKVSr8xxtwzSureiskb5/98moAiutpUtp15yyAm0
            rwIDAQAB
            -----END PUBLIC KEY-----
        image: islandora/gemini:latest
        name: gemini
        resources: {}
      restartPolicy: Always
status: {}
